# Generated by Django 4.0.3 on 2022-03-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='user',
            new_name='teacher',
        ),
    ]
